Libname LWFETSP "C:\TimeSeriesData\"; 

*proc contents nods data=LWFETSP._all_; 
*title "Current LWFETSP data sets"; 
*run; 

*proc contents data=LWFETSP.us_retail_sales;
*run;

*proc freq data=LWFETSP.us_retail_sales nlevels;
*run;

ods graphics on / imagemap=on;

***CREATE REGRESSION OF SALES OVER TIME***;
PROC REG DATA=LWFETSP.US_Retail_Sales; 
  MODEL SALES = T; 
    OUTPUT OUT=WORK.SALESOUT1 PREDICTED=P RESIDUAL=R LCL=L95I UCL=U95I LCLM=L95M UCLM=U95M; 
run; quit;

***CREATE PLOT OF PREDICTIONS VS. OBSERVED VALUES***;
PROC SGPLOT DATA=SALESOUT1; 
    SERIES X=DATE Y=P; 
	SCATTER X=DATE Y=SALES;
RUN;

***CREATE PLOT OF RESIDUALS***;
PROC SGPLOT DATA=SALESOUT1; 
    SERIES X=DATE Y=R; 
RUN;

***CREATE REGRESSION OF SALES OVER TIME WITH MONTHLY DUMMY***;
PROC REG DATA=LWFETSP.US_Retail_Sales; 
  MODEL SALES = T MON1-MON11; 
    OUTPUT OUT=WORK.SALESOUT2 PREDICTED=P RESIDUAL=R LCL=L95I UCL=U95I LCLM=L95M UCLM=U95M; 
run; quit;

***CREATE PLOT OF PREDICTIONS VS. OBSERVED VALUES***;
PROC SGPLOT DATA=SALESOUT2; 
    SERIES X=DATE Y=P; 
	SCATTER X=DATE Y=SALES;
RUN;

***CREATE PLOT OF RESIDUALS***;
PROC SGPLOT DATA=SALESOUT2; 
    SERIES X=DATE Y=R; 
RUN;

***CREATE REGRESSION OF SALES OVER TIME WITH MONTHLY DUMMY & STRUCTURAL RAMP***;
PROC REG DATA=LWFETSP.US_Retail_Sales; 
  MODEL SALES = T MON1-MON11 ramp; 
    OUTPUT OUT=WORK.SALESOUT3 PREDICTED=P RESIDUAL=R LCL=L95I UCL=U95I LCLM=L95M UCLM=U95M; 
run; quit;

***CREATE A PLOT OF RAMP OVER TIME***;
PROC SGPLOT DATA=LWFETSP.US_Retail_Sales;
	SERIES X=DATE Y=RAMP;
RUN;

***CREATE PLOT OF PREDICTIONS VS. OBSERVED VALUES***;
PROC SGPLOT DATA=SALESOUT3;
    SERIES X=DATE Y=P; 
	SCATTER X=DATE Y=SALES;
RUN;

***CREATE PLOT OF RESIDUALS***;
PROC SGPLOT DATA=SALESOUT3; 
    SERIES X=DATE Y=R; 
RUN;

***CLI VS. CLM BANDS***;

***CREATE PLOT OF PREDICTIONS VS. OBSERVED VALUES***;
PROC SGPLOT DATA=SALESOUT3;
	BAND X=DATE lower=L95I upper=U95I / legendlabel='95% CLI' fillattrs=(COLOR=red);
    SERIES X=DATE Y=P; 
	SCATTER X=DATE Y=SALES;
RUN;

***CREATE PLOT OF PREDICTIONS VS. OBSERVED VALUES***;
PROC SGPLOT DATA=SALESOUT3;
	BAND X=DATE lower=L95M upper=U95I / legendlabel='95% CLM' fillattrs=(COLOR=green);
    SERIES X=DATE Y=P; 
	SCATTER X=DATE Y=SALES;
RUN;

***SUBSET DATA BEFORE AND AFTER RAMP VARIABLE ADDED***;
data precrisis postcrisis;
	set LWFETSP.US_Retail_Sales;
	if ramp=0 then output precrisis;
	if ramp^=0 then output postcrisis;
run; 

***PRE-CRISIS REGRESSION***;
PROC REG DATA=precrisis; 
  MODEL SALES = T MON1-MON11; 
    OUTPUT OUT=WORK.SALESOUT4 PREDICTED=P RESIDUAL=R LCL=L95I UCL=U95I LCLM=L95M UCLM=U95M; 
run; quit;

***POST-CRISIS REGRESSION***;
PROC REG DATA=postcrisis; 
  MODEL SALES = T MON1-MON11 ramp; 
    OUTPUT OUT=WORK.SALESOUT5 PREDICTED=P RESIDUAL=R LCL=L95I UCL=U95I LCLM=L95M UCLM=U95M; 
run; quit;
